"""empty message

Revision ID: 2a4eb70f8366
Revises: c1d5e0883973
Create Date: 2016-05-26 13:17:33.684983

"""

# revision identifiers, used by Alembic.
revision = '2a4eb70f8366'
down_revision = 'c1d5e0883973'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_service_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_service_mapping')
    ### end Alembic commands ###
