"""empty message

Revision ID: 403d6cc04754
Revises: 4efb88fd0656
Create Date: 2016-08-18 14:48:16.323950

"""

# revision identifiers, used by Alembic.
revision = '403d6cc04754'
down_revision = '4efb88fd0656'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('access_log', sa.Column('sni', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'sni')
    op.drop_column('access_log', 'length')
    ### end Alembic commands ###
