"""empty message

Revision ID: 4efb88fd0656
Revises: None
Create Date: 2016-08-18 13:19:20.765904

"""

# revision identifiers, used by Alembic.
revision = '4efb88fd0656'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_service_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"timezone('utc'::text, now())"), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connect_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"timezone('utc'::text, now())"), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('interface', sa.String(length=30), nullable=True),
    sa.Column('local_ip', postgresql.INET(), nullable=True),
    sa.Column('remote_ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('interface', sa.String(length=30), nullable=True),
    sa.Column('local_ip', postgresql.INET(), nullable=True),
    sa.Column('remote_ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('connect_log')
    op.drop_table('access_log')
    op.drop_table('user')
    op.drop_table('host_service_mapping')
    ### end Alembic commands ###
