"""empty message

Revision ID: 905272ff467b
Revises: None
Create Date: 2016-05-25 00:59:03.541801

"""

# revision identifiers, used by Alembic.
revision = '905272ff467b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_index('connect_log_username_idx', table_name='connect_log')
    op.add_column('user', sa.Column('role', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.create_index('connect_log_username_idx', 'connect_log', ['username'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('interface', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('local_ip', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('remote_ip', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'sessions_pkey')
    )
    ### end Alembic commands ###
