"""empty message

Revision ID: c1d5e0883973
Revises: 905272ff467b
Create Date: 2016-05-26 03:15:21.218301

"""

# revision identifiers, used by Alembic.
revision = 'c1d5e0883973'
down_revision = '905272ff467b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('interface', sa.String(length=30), nullable=True),
    sa.Column('local_ip', postgresql.INET(), nullable=True),
    sa.Column('remote_ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'access_log', 'user', ['username'], ['username'])
    op.create_foreign_key(None, 'connect_log', 'user', ['username'], ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connect_log', type_='foreignkey')
    op.drop_constraint(None, 'access_log', type_='foreignkey')
    op.drop_table('sessions')
    ### end Alembic commands ###
